### ISSUE TITLE
can you provide the checkpoint of pyramidnet trained in the cifar10?

### ISSUE THREAD

**Issue by johsnows** [ecs-vlc/FMix#20]
can you provide the checkpoint of pyramidnet trained in the cifar10?thank you!

**Comment by ethanwharris** [comment]
Sure, it's all available via pytorch-hub, just follow the intstructions from the [pretrained models section in the readme](https://github.com/ecs-vlc/FMix#pre-trained-models).

Alternatively you can use:
```
wget 'http://marc.ecs.soton.ac.uk/pytorch-models/cifar10/pyramidnet/cifar10_pyramidnet_fmix.pt'
```
if you just need the file.

Hope that helps!
