### ISSUE TITLE
For MSDA between images, my mask is always a vertical block.

### ISSUE THREAD

**Issue by 1094558673** [ecs-vlc/FMix#26]
I just use the def in fmix.py to generate blended images independently using a batch-size images.  But the end result is always a mix of vertical blocks, just like the cutmix. I didn't use pytorch or tf, just the fmix.py and pass in batch data alone. I don't know what the problem is, if you can help me to answer this question, I would be very grateful.

**Comment by ethanwharris** [comment]
Hi, thanks for the issue. Could you provide some code showing the behaviour you describe? That will be easier for us to help with

**Comment by 1094558673** [comment]
Thank you very much for your reply, I just realized that I had mixed up the channels(HxWxC and CxHxW). Now it works!
And i just have another question: for object detection problems, can FMix make changes to the ground truth box at the same time, or we need to make manual annotation again?
Thanks again for your reply and answer！

**Comment by ethanwharris** [comment]
No problem, glad you got it working 😃 regarding object detection, we did look at trying to extend it to object detection but could never figure out how to do it. You would need a way of mixing the bounding boxes based on the mask which would be a bit tricky, but let us know if you find something that works!
